### ISSUE TITLE
Switch Rcpp Vignette Engine away from highlight

### ISSUE THREAD

**Issue by coatless** [RcppCore/Rcpp#604]
Rcpp vignettes presently uses the [highlight](https://cloud.r-project.org/web/packages/highlight/index.html) package that mandates a [non-standard approach](https://github.com/RcppCore/Rcpp/wiki/Modifying-an-Rcpp-Vignette) to rendering the documentation.

Switching away from this engine to either `knitr` or `rmarkdown` requires...

## Knitr 

In each vignette, the following must be changed:
```
%\VignetteEngine{highlight::highlight}
```

To 

```
%\VignetteEngine{knitr::knitr}
```

In the `DESCRIPTION` file replace:

```
VignetteBuilder: highlight
```

with 

```
VignetteBuilder: knitr
```

And add 

```
Suggests: knitr
```

Switch each code chunk to use knitr options:

```
<<>>=
@
```

## RMarkdown

In each vignette, YML matter must be added:

```
---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
```

The `rmarkdown::html_vignette` can be customized using [RMarkdown Templates](http://rmarkdown.rstudio.com/developer_document_templates.html) (I've had success with [uiucthemes](http://github.com/coatless/uiucthemes)). So, the current Rcpp vignette style could be ported to an embedded style function call. 

In addition, code segments must be switched over to using the GFM code ticked fence design. 

However, this involves more work potentially porting over LaTeX syntax to use native RMarkdown to take full advantage of the format.  

Related to #506 and should be associated with #602

**Comment by coatless** [comment]
Probably going to go down the RMarkdown route.

The main issue is the custom syntax in a few files (e.g. `\sugar`) would only really be viable in LaTeX unless there is a way to custom define syntax for multiple renders that I've overlooked... 

Outside of that, using [parameterized reports](http://rmarkdown.rstudio.com/developer_parameterized_reports.html) the date and version information can easily be placed within the document. 

```
---
title: "Rcpp syntactic sugar"
author: 'Dirk Eddelbuettel and Romain François'
date: '`r paste("Rcpp version", params$prettyVersion, "as of", params$prettyDate)`'
output:
  rcpp_vignette
params:
  prettyDate: !r format(Sys.Date(), "%B %e, %Y")
  prettyVersion: !r packageDescription("Rcpp")$Version
bibliography: Rcpp.bib
---
```
